### ISSUE TITLE
请问你们这个方法是否适用于targeted attack？

### ISSUE THREAD

**Issue by Juli-Eyre** [winterwindwang/Data-efficient-UAP#1]
作者您好，非常感谢你们的工作！我想请教下你们的方法（扰乱特征）能否用于有目标攻击？
(新手，非常感谢您的解答~)

**Comment by winterwindwang** [comment]
> 作者您好，非常感谢你们的工作！我想请教下你们的方法（扰乱特征）能否用于有目标攻击？ (新手，非常感谢您的解答~)

我们的方法没有考虑目标攻击，这也是我们方法的一个缺点。但是可以尝试一下通过强化目标类别的特征（可以利用目标类别的梯度来筛选）来优化通用对抗扰动。
