### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by tanlingp** [winterwindwang/Data-efficient-UAP#2]
请问你能够提供实验中涉及的数据集吗？

**Comment by winterwindwang** [comment]
实验所用数据集都是公开数据集。训练集是从数据集随机采样得到的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月2日(周六) 下午2:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [winterwindwang/Data-efficient-UAP] 数据集 (Issue #2)




 
请问你能够提供实验中涉及的数据集吗？

**Comment by tanlingp** [comment]
本人认为训练数据集里面的图片不同可能会影响实验效果，因此希望你能够将你采样的数据集公布出来。非常感谢

**Comment by winterwindwang** [comment]
你好，这个[imagenet10k](https://github.com/winterwindwang/Data-efficient-UAP/blob/main/dataset/imagenet10k.txt)是我们在实验中所使用的从ImageNet训练集中随机采样的10000张图片的信息，你可以根据这些信息从ImageNet训练集中赛选出相应的数据。至于其他数据集，我们则是从训练集中随机采样的特定数量的图片作为训练集合。
